In [1]:
# SVC Algorithm

In [1]:
pip install -q  missingno

Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as ms
%matplotlib inline

In [4]:
pip install -q seaborn

Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as ms
%matplotlib inline

In [3]:
!wget https://www.dropbox.com/s/ikyxo0zew514a0b/processes_datasets.csv

--2019-03-14 03:07:03--  https://www.dropbox.com/s/ikyxo0zew514a0b/processes_datasets.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.1.1, 2620:100:6016:1::a27d:101
Connecting to www.dropbox.com (www.dropbox.com)|162.125.1.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/ikyxo0zew514a0b/processes_datasets.csv [following]
--2019-03-14 03:07:03--  https://www.dropbox.com/s/raw/ikyxo0zew514a0b/processes_datasets.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucca1cc5469af941e677eecdfecb.dl.dropboxusercontent.com/cd/0/inline/AdCHApSvfm1WjbY6cElx5O3I_5cRcGgFh-ItI8-5hAxNfpJYn4qlizMvkhENO6tyiKSbRGLba-MOPiXdLeU2ecvDJ6kmx2-XPXdqAHSZnqDI4w/file# [following]
--2019-03-14 03:07:03--  https://ucca1cc5469af941e677eecdfecb.dl.dropboxusercontent.com/cd/0/inline/AdCHApSvfm1WjbY6cElx5O3I_5cRcGgFh-ItI8-5hAxNfpJYn4qlizMvkhENO6tyiKSbRGLba-MOPiXdLeU2ecvDJ6kmx2-XPXdqAHSZnqDI4w/file
Resolving ucca1cc5469af941e677eecdfecb.dl.dropboxusercontent.com (ucca1cc5469af941e677eecdfecb.dl.dropboxusercontent.com)... 162.125.1.6, 2620:100:601b:6::a27d:806
Connecting to ucca1cc5469af941e677eecdfecb.dl.dropboxusercontent.com (ucca1cc5469af941e677eecdfecb.dl.dropboxusercontent.com)|162.125.1.6|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 49425441 (47M) [text/plain]
Saving to: ‘processes_datasets.csv’

processes_datasets. 100%[===================>]  47.14M  74.8MB/s    in 0.6s

2019-03-14 03:07:04 (74.8 MB/s) - ‘processes_datasets.csv’ saved [49425441/49425441]

In [5]:
data = pd.read_csv('processes_datasets.csv')

In [6]:
data.drop(['JobStructure','JobStructureParams','UsedNetwork','UsedLocalDiskSpace','UsedResources','ReqPlatform','ReqNetwork',
          'ReqLocalDiskSpace','ReqResources','VOID','ProjectID'],axis=1,inplace=True)

In [7]:
data.head()

,JobID,SubmitTime,WaitTime,RunTime,NProcs,AverageCPUTimeUsed,Used Memory,ReqNProcs,ReqTime:,ReqMemory,Status,UserID,GroupID,ExecutableID,QueueID,PartitionID,OrigSiteID,LastRunSiteID
0,1,1136070024,203761,138467,1,138371,98652,1,259200,-1,1,U2004S1,G3,X1,Q5,1,clrlcgce02,clrlcgce02
1,2,1136070690,0,11,1,4,35848,1,259200,-1,1,U1023S0,G1,X1,Q1,1,clrlcgce01,clrlcgce01
2,3,1136071207,117,201203,1,0,0,1,259200,-1,1,U2035S1,G6,X1,Q2,1,clrlcgce02,clrlcgce02
3,4,1136071267,4406,196985,1,0,0,1,259200,-1,1,U2035S1,G6,X1,Q2,1,clrlcgce02,clrlcgce02
4,5,1136071269,202516,19520,1,18731,522268,1,259200,-1,1,U2035S1,G6,X1,Q2,1,clrlcgce02,clrlcgce02

In [8]:
data['QueueNO'] = data['QueueID'].rank(method='dense', ascending=False).astype(int)
data['GroupNO'] = data['GroupID'].rank(method='dense', ascending=False).astype(int)
data['ExecutableNO'] = data['ExecutableID'].rank(method='dense', ascending=False).astype(int)
data['OrigSiteNO'] = data['OrigSiteID'].rank(method='dense', ascending=False).astype(int)
data['LastRunSiteNO'] = data['LastRunSiteID'].rank(method='dense', ascending=False).astype(int)
data.head()

,JobID,SubmitTime,WaitTime,RunTime,NProcs,AverageCPUTimeUsed,Used Memory,ReqNProcs,ReqTime:,ReqMemory,...,ExecutableID,QueueID,PartitionID,OrigSiteID,LastRunSiteID,QueueNO,GroupNO,ExecutableNO,OrigSiteNO,LastRunSiteNO
0,1,1136070024,203761,138467,1,138371,98652,1,259200,-1,...,X1,Q5,1,clrlcgce02,clrlcgce02,5,6,15,4,4
1,2,1136070690,0,11,1,4,35848,1,259200,-1,...,X1,Q1,1,clrlcgce01,clrlcgce01,13,8,15,5,5
2,3,1136071207,117,201203,1,0,0,1,259200,-1,...,X1,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4
3,4,1136071267,4406,196985,1,0,0,1,259200,-1,...,X1,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4
4,5,1136071269,202516,19520,1,18731,522268,1,259200,-1,...,X1,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4

In [9]:
data['USERNO'] = data['UserID'].rank(method='dense', ascending=False).astype(int)
data.head()

,JobID,SubmitTime,WaitTime,RunTime,NProcs,AverageCPUTimeUsed,Used Memory,ReqNProcs,ReqTime:,ReqMemory,...,QueueID,PartitionID,OrigSiteID,LastRunSiteID,QueueNO,GroupNO,ExecutableNO,OrigSiteNO,LastRunSiteNO,USERNO
0,1,1136070024,203761,138467,1,138371,98652,1,259200,-1,...,Q5,1,clrlcgce02,clrlcgce02,5,6,15,4,4,272
1,2,1136070690,0,11,1,4,35848,1,259200,-1,...,Q1,1,clrlcgce01,clrlcgce01,13,8,15,5,5,378
2,3,1136071207,117,201203,1,0,0,1,259200,-1,...,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4,238
3,4,1136071267,4406,196985,1,0,0,1,259200,-1,...,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4,238
4,5,1136071269,202516,19520,1,18731,522268,1,259200,-1,...,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4,238

In [10]:
data.drop(['UserID','QueueID','GroupID','ExecutableID','OrigSiteID','LastRunSiteID'],axis=1,inplace=True)

In [19]:
data.head()

,JobID,SubmitTime,WaitTime,RunTime,NProcs,AverageCPUTimeUsed,Used Memory,ReqNProcs,ReqTime:,ReqMemory,Status,PartitionID,QueueNO,GroupNO,ExecutableNO,OrigSiteNO,LastRunSiteNO,USERNO
0,1,1136070024,203761,138467,1,138371,98652,1,259200,-1,1,1,5,6,15,4,4,272
1,2,1136070690,0,11,1,4,35848,1,259200,-1,1,1,13,8,15,5,5,378
2,3,1136071207,117,201203,1,0,0,1,259200,-1,1,1,8,3,15,4,4,238
3,4,1136071267,4406,196985,1,0,0,1,259200,-1,1,1,8,3,15,4,4,238
4,5,1136071269,202516,19520,1,18731,522268,1,259200,-1,1,1,8,3,15,4,4,238

In [20]:
X = data.drop('RunTime ',axis=1)
y = data['RunTime ']

In [13]:
X.head()

,JobID,SubmitTime,WaitTime,NProcs,AverageCPUTimeUsed,Used Memory,ReqNProcs,ReqTime:,ReqMemory,Status,PartitionID,QueueNO,GroupNO,ExecutableNO,OrigSiteNO,LastRunSiteNO,USERNO
0,1,1136070024,203761,1,138371,98652,1,259200,-1,1,1,5,6,15,4,4,272
1,2,1136070690,0,1,4,35848,1,259200,-1,1,1,13,8,15,5,5,378
2,3,1136071207,117,1,0,0,1,259200,-1,1,1,8,3,15,4,4,238
3,4,1136071267,4406,1,0,0,1,259200,-1,1,1,8,3,15,4,4,238
4,5,1136071269,202516,1,18731,522268,1,259200,-1,1,1,8,3,15,4,4,238

In [21]:
from sklearn import preprocessing

In [22]:
min_max_scaler = preprocessing.MinMaxScaler()

In [23]:
X_minmax = min_max_scaler.fit_transform(X)

In [24]:
from sklearn.model_selection import train_test_split

In [30]:
X1, X1, y1, y2 = train_test_split(X_minmax,y 
                                                    , test_size=0.95,random_state=50)

In [33]:
X1

array([[6.53343230e-01, 6.40255417e-01, 1.12843622e-02, ...,
        5.00000000e-01, 5.00000000e-01, 3.19306931e-01],
       [3.60648234e-01, 4.29945574e-01, 5.68993283e-03, ...,
        5.00000000e-01, 5.00000000e-01, 1.23762376e-01],
       [4.22267582e-02, 1.05706803e-01, 4.60257459e-07, ...,
        1.00000000e+00, 1.00000000e+00, 9.85148515e-01],
       ...,
       [5.11328014e-01, 5.21235666e-01, 2.41635166e-05, ...,
        5.00000000e-01, 5.00000000e-01, 3.01980198e-01],
       [3.45832869e-01, 4.22304377e-01, 0.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 8.86138614e-01],
       [7.54507330e-01, 7.43881376e-01, 4.28016424e-03, ...,
        1.00000000e+00, 1.00000000e+00, 1.23762376e-01]])

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X_minmax,y 
                                                    , test_size=0.30,random_state=50)

In [26]:
from sklearn import tree

In [27]:
clf = tree.DecisionTreeClassifier()

In [21]:
classifier = SVC(C=10, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [28]:
clf = clf.fit(X_train,y_train)

MemoryError: could not allocate 18008244224 bytes

In [21]:
clf

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [ ]:
y_pred_tree = classifier.predict(X_test)

In [ ]:
#Evaluation

In [ ]:
from sklearn.metrics import  accuracy_score, r2_score

In [ ]:
np.corrcoef(y_pred_tree,y_test)

In [ ]:
r2_score(y_pred_tree, y_test)