In [1]:
# SVC Algorithm

In [4]:
pip install -q  missingno

Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as ms
%matplotlib inline

In [6]:
pip install -q seaborn

Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as ms
%matplotlib inline

In [8]:
!wget https://www.dropbox.com/s/ikyxo0zew514a0b/processes_datasets.csv

--2019-03-20 04:36:29--  https://www.dropbox.com/s/ikyxo0zew514a0b/processes_datasets.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.8.1, 2620:100:6016:1::a27d:101
Connecting to www.dropbox.com (www.dropbox.com)|162.125.8.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/ikyxo0zew514a0b/processes_datasets.csv [following]
--2019-03-20 04:36:29--  https://www.dropbox.com/s/raw/ikyxo0zew514a0b/processes_datasets.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucffc0b729e4b6518035bcca6fcd.dl.dropboxusercontent.com/cd/0/inline/AdbrmuH3_MllKwVKecPiF-HL9cinIiTkEueOykFS_4ufepiE89Lv1ef3eklmg1jotMvNHlNnxAdQhBNSA0zzdkJs7P7nHbz3TZkdw-oXiMeWiw/file# [following]
--2019-03-20 04:36:29--  https://ucffc0b729e4b6518035bcca6fcd.dl.dropboxusercontent.com/cd/0/inline/AdbrmuH3_MllKwVKecPiF-HL9cinIiTkEueOykFS_4ufepiE89Lv1ef3eklmg1jotMvNHlNnxAdQhBNSA0zzdkJs7P7nHbz3TZkdw-oXiMeWiw/file
Resolving ucffc0b729e4b6518035bcca6fcd.dl.dropboxusercontent.com (ucffc0b729e4b6518035bcca6fcd.dl.dropboxusercontent.com)... 162.125.1.6, 2620:100:601b:6::a27d:806
Connecting to ucffc0b729e4b6518035bcca6fcd.dl.dropboxusercontent.com (ucffc0b729e4b6518035bcca6fcd.dl.dropboxusercontent.com)|162.125.1.6|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 49425441 (47M) [text/plain]
Saving to: ‘processes_datasets.csv.2’

processes_datasets. 100%[===================>]  47.14M  79.3MB/s    in 0.6s

2019-03-20 04:36:30 (79.3 MB/s) - ‘processes_datasets.csv.2’ saved [49425441/49425441]

In [9]:
data = pd.read_csv('processes_datasets.csv')

In [10]:
data.drop(['JobStructure','JobStructureParams','UsedNetwork','UsedLocalDiskSpace','UsedResources','ReqPlatform','ReqNetwork',
          'ReqLocalDiskSpace','ReqResources','VOID','ProjectID'],axis=1,inplace=True)

In [11]:
data.head()

,JobID,SubmitTime,WaitTime,RunTime,NProcs,AverageCPUTimeUsed,Used Memory,ReqNProcs,ReqTime:,ReqMemory,Status,UserID,GroupID,ExecutableID,QueueID,PartitionID,OrigSiteID,LastRunSiteID
0,1,1136070024,203761,138467,1,138371,98652,1,259200,-1,1,U2004S1,G3,X1,Q5,1,clrlcgce02,clrlcgce02
1,2,1136070690,0,11,1,4,35848,1,259200,-1,1,U1023S0,G1,X1,Q1,1,clrlcgce01,clrlcgce01
2,3,1136071207,117,201203,1,0,0,1,259200,-1,1,U2035S1,G6,X1,Q2,1,clrlcgce02,clrlcgce02
3,4,1136071267,4406,196985,1,0,0,1,259200,-1,1,U2035S1,G6,X1,Q2,1,clrlcgce02,clrlcgce02
4,5,1136071269,202516,19520,1,18731,522268,1,259200,-1,1,U2035S1,G6,X1,Q2,1,clrlcgce02,clrlcgce02

In [12]:
data['QueueNO'] = data['QueueID'].rank(method='dense', ascending=False).astype(int)
data['GroupNO'] = data['GroupID'].rank(method='dense', ascending=False).astype(int)
data['ExecutableNO'] = data['ExecutableID'].rank(method='dense', ascending=False).astype(int)
data['OrigSiteNO'] = data['OrigSiteID'].rank(method='dense', ascending=False).astype(int)
data['LastRunSiteNO'] = data['LastRunSiteID'].rank(method='dense', ascending=False).astype(int)
data.head()

,JobID,SubmitTime,WaitTime,RunTime,NProcs,AverageCPUTimeUsed,Used Memory,ReqNProcs,ReqTime:,ReqMemory,...,ExecutableID,QueueID,PartitionID,OrigSiteID,LastRunSiteID,QueueNO,GroupNO,ExecutableNO,OrigSiteNO,LastRunSiteNO
0,1,1136070024,203761,138467,1,138371,98652,1,259200,-1,...,X1,Q5,1,clrlcgce02,clrlcgce02,5,6,15,4,4
1,2,1136070690,0,11,1,4,35848,1,259200,-1,...,X1,Q1,1,clrlcgce01,clrlcgce01,13,8,15,5,5
2,3,1136071207,117,201203,1,0,0,1,259200,-1,...,X1,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4
3,4,1136071267,4406,196985,1,0,0,1,259200,-1,...,X1,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4
4,5,1136071269,202516,19520,1,18731,522268,1,259200,-1,...,X1,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4

In [13]:
data['USERNO'] = data['UserID'].rank(method='dense', ascending=False).astype(int)
data.head()

,JobID,SubmitTime,WaitTime,RunTime,NProcs,AverageCPUTimeUsed,Used Memory,ReqNProcs,ReqTime:,ReqMemory,...,QueueID,PartitionID,OrigSiteID,LastRunSiteID,QueueNO,GroupNO,ExecutableNO,OrigSiteNO,LastRunSiteNO,USERNO
0,1,1136070024,203761,138467,1,138371,98652,1,259200,-1,...,Q5,1,clrlcgce02,clrlcgce02,5,6,15,4,4,272
1,2,1136070690,0,11,1,4,35848,1,259200,-1,...,Q1,1,clrlcgce01,clrlcgce01,13,8,15,5,5,378
2,3,1136071207,117,201203,1,0,0,1,259200,-1,...,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4,238
3,4,1136071267,4406,196985,1,0,0,1,259200,-1,...,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4,238
4,5,1136071269,202516,19520,1,18731,522268,1,259200,-1,...,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4,238

In [14]:
data.drop(['UserID','QueueID','GroupID','ExecutableID','OrigSiteID','LastRunSiteID'],axis=1,inplace=True)

In [15]:
data.head()

,JobID,SubmitTime,WaitTime,RunTime,NProcs,AverageCPUTimeUsed,Used Memory,ReqNProcs,ReqTime:,ReqMemory,Status,PartitionID,QueueNO,GroupNO,ExecutableNO,OrigSiteNO,LastRunSiteNO,USERNO
0,1,1136070024,203761,138467,1,138371,98652,1,259200,-1,1,1,5,6,15,4,4,272
1,2,1136070690,0,11,1,4,35848,1,259200,-1,1,1,13,8,15,5,5,378
2,3,1136071207,117,201203,1,0,0,1,259200,-1,1,1,8,3,15,4,4,238
3,4,1136071267,4406,196985,1,0,0,1,259200,-1,1,1,8,3,15,4,4,238
4,5,1136071269,202516,19520,1,18731,522268,1,259200,-1,1,1,8,3,15,4,4,238

In [16]:
X = data.drop('RunTime ',axis=1)
y = data['RunTime ']

In [17]:
X.head()

,JobID,SubmitTime,WaitTime,NProcs,AverageCPUTimeUsed,Used Memory,ReqNProcs,ReqTime:,ReqMemory,Status,PartitionID,QueueNO,GroupNO,ExecutableNO,OrigSiteNO,LastRunSiteNO,USERNO
0,1,1136070024,203761,1,138371,98652,1,259200,-1,1,1,5,6,15,4,4,272
1,2,1136070690,0,1,4,35848,1,259200,-1,1,1,13,8,15,5,5,378
2,3,1136071207,117,1,0,0,1,259200,-1,1,1,8,3,15,4,4,238
3,4,1136071267,4406,1,0,0,1,259200,-1,1,1,8,3,15,4,4,238
4,5,1136071269,202516,1,18731,522268,1,259200,-1,1,1,8,3,15,4,4,238

In [18]:
from sklearn import preprocessing

In [19]:
min_max_scaler = preprocessing.MinMaxScaler()

In [20]:
X_minmax = min_max_scaler.fit_transform(X)

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X_minmax,y 
                                                    , test_size=0.30,random_state=50)

In [23]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=4)

In [25]:
#Train the model using the training sets
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=4, p=2,
           weights='uniform')

In [26]:
knn.score(X_test, y_test)

0.23067470495575368

In [27]:
#Predict the response for test dataset
y_pred_knn = knn.predict(X_test)

In [ ]:
from sklearn.metrics import  accuracy_score, r2_score

In [ ]:
np.corrcoef(y_pred,y_test)

In [ ]:
r2_score(y_pred, y_test)