In [1]:
# SVC Algorithm

In [ ]:
pip install -q  missingno

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as ms
%matplotlib inline

In [ ]:
pip install -q seaborn

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as ms
%matplotlib inline

In [ ]:
!wget https://www.dropbox.com/s/ikyxo0zew514a0b/processes_datasets.csv

In [ ]:
data = pd.read_csv('processes_datasets.csv')

In [7]:
data.drop(['JobStructure','JobStructureParams','UsedNetwork','UsedLocalDiskSpace','UsedResources','ReqPlatform','ReqNetwork',
          'ReqLocalDiskSpace','ReqResources','VOID','ProjectID'],axis=1,inplace=True)

In [8]:
data.head()

,JobID,SubmitTime,WaitTime,RunTime,NProcs,AverageCPUTimeUsed,Used Memory,ReqNProcs,ReqTime:,ReqMemory,Status,UserID,GroupID,ExecutableID,QueueID,PartitionID,OrigSiteID,LastRunSiteID
0,1,1136070024,203761,138467,1,138371,98652,1,259200,-1,1,U2004S1,G3,X1,Q5,1,clrlcgce02,clrlcgce02
1,2,1136070690,0,11,1,4,35848,1,259200,-1,1,U1023S0,G1,X1,Q1,1,clrlcgce01,clrlcgce01
2,3,1136071207,117,201203,1,0,0,1,259200,-1,1,U2035S1,G6,X1,Q2,1,clrlcgce02,clrlcgce02
3,4,1136071267,4406,196985,1,0,0,1,259200,-1,1,U2035S1,G6,X1,Q2,1,clrlcgce02,clrlcgce02
4,5,1136071269,202516,19520,1,18731,522268,1,259200,-1,1,U2035S1,G6,X1,Q2,1,clrlcgce02,clrlcgce02

In [9]:
data['QueueNO'] = data['QueueID'].rank(method='dense', ascending=False).astype(int)
data['GroupNO'] = data['GroupID'].rank(method='dense', ascending=False).astype(int)
data['ExecutableNO'] = data['ExecutableID'].rank(method='dense', ascending=False).astype(int)
data['OrigSiteNO'] = data['OrigSiteID'].rank(method='dense', ascending=False).astype(int)
data['LastRunSiteNO'] = data['LastRunSiteID'].rank(method='dense', ascending=False).astype(int)
data.head()

,JobID,SubmitTime,WaitTime,RunTime,NProcs,AverageCPUTimeUsed,Used Memory,ReqNProcs,ReqTime:,ReqMemory,...,ExecutableID,QueueID,PartitionID,OrigSiteID,LastRunSiteID,QueueNO,GroupNO,ExecutableNO,OrigSiteNO,LastRunSiteNO
0,1,1136070024,203761,138467,1,138371,98652,1,259200,-1,...,X1,Q5,1,clrlcgce02,clrlcgce02,5,6,15,4,4
1,2,1136070690,0,11,1,4,35848,1,259200,-1,...,X1,Q1,1,clrlcgce01,clrlcgce01,13,8,15,5,5
2,3,1136071207,117,201203,1,0,0,1,259200,-1,...,X1,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4
3,4,1136071267,4406,196985,1,0,0,1,259200,-1,...,X1,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4
4,5,1136071269,202516,19520,1,18731,522268,1,259200,-1,...,X1,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4

In [10]:
data['USERNO'] = data['UserID'].rank(method='dense', ascending=False).astype(int)
data.head()

,JobID,SubmitTime,WaitTime,RunTime,NProcs,AverageCPUTimeUsed,Used Memory,ReqNProcs,ReqTime:,ReqMemory,...,QueueID,PartitionID,OrigSiteID,LastRunSiteID,QueueNO,GroupNO,ExecutableNO,OrigSiteNO,LastRunSiteNO,USERNO
0,1,1136070024,203761,138467,1,138371,98652,1,259200,-1,...,Q5,1,clrlcgce02,clrlcgce02,5,6,15,4,4,272
1,2,1136070690,0,11,1,4,35848,1,259200,-1,...,Q1,1,clrlcgce01,clrlcgce01,13,8,15,5,5,378
2,3,1136071207,117,201203,1,0,0,1,259200,-1,...,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4,238
3,4,1136071267,4406,196985,1,0,0,1,259200,-1,...,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4,238
4,5,1136071269,202516,19520,1,18731,522268,1,259200,-1,...,Q2,1,clrlcgce02,clrlcgce02,8,3,15,4,4,238

In [11]:
data.drop(['UserID','QueueID','GroupID','ExecutableID','OrigSiteID','LastRunSiteID'],axis=1,inplace=True)

In [10]:
data.head()

,JobID,SubmitTime,WaitTime,RunTime,NProcs,AverageCPUTimeUsed,Used Memory,ReqNProcs,ReqTime:,ReqMemory,Status,PartitionID,QueueNO,GroupNO,ExecutableNO,OrigSiteNO,LastRunSiteNO,USERNO
0,1,1136070024,203761,138467,1,138371,98652,1,259200,-1,1,1,5,6,15,4,4,272
1,2,1136070690,0,11,1,4,35848,1,259200,-1,1,1,13,8,15,5,5,378
2,3,1136071207,117,201203,1,0,0,1,259200,-1,1,1,8,3,15,4,4,238
3,4,1136071267,4406,196985,1,0,0,1,259200,-1,1,1,8,3,15,4,4,238
4,5,1136071269,202516,19520,1,18731,522268,1,259200,-1,1,1,8,3,15,4,4,238

In [12]:
X = data.drop('RunTime ',axis=1)
y = data['RunTime ']

In [13]:
X.head()

,JobID,SubmitTime,WaitTime,NProcs,AverageCPUTimeUsed,Used Memory,ReqNProcs,ReqTime:,ReqMemory,Status,PartitionID,QueueNO,GroupNO,ExecutableNO,OrigSiteNO,LastRunSiteNO,USERNO
0,1,1136070024,203761,1,138371,98652,1,259200,-1,1,1,5,6,15,4,4,272
1,2,1136070690,0,1,4,35848,1,259200,-1,1,1,13,8,15,5,5,378
2,3,1136071207,117,1,0,0,1,259200,-1,1,1,8,3,15,4,4,238
3,4,1136071267,4406,1,0,0,1,259200,-1,1,1,8,3,15,4,4,238
4,5,1136071269,202516,1,18731,522268,1,259200,-1,1,1,8,3,15,4,4,238

In [14]:
from sklearn import preprocessing

In [15]:
min_max_scaler = preprocessing.MinMaxScaler()

In [16]:
X_minmax = min_max_scaler.fit_transform(X)

In [17]:
from sklearn.model_selection import train_test_split

In [ ]:
X1, X2, y1, y2 = train_test_split(X_minmax,y,test_size=0.95)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X_minmax,y 
                                                    , test_size=0.30,random_state=50)

In [ ]:
X1.head()

In [19]:
from sklearn.svm import SVC

In [20]:
clf = SVC(kernel='linear')

In [21]:
classifier = SVC(C=10, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [ ]:
classifier.fit(X_train,y_train)

In [21]:
classifier

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [ ]:
y_pred_svc = classifier.predict(X_test)

In [ ]:
#Evaluation

In [ ]:
from sklearn.metrics import  accuracy_score, r2_score

In [ ]:
np.corrcoef(y_pred_svc,y_test)

In [ ]:
r2_score(y_pred_svc, y_test)